// sandbox/vue/App.vue
<template>
  <div id="app">
    <h1>vue-inner-image-zoom Sandbox</h1>

    <section>
      <h2>Pan Demo</h2>

      <demo
        src="https://images.unsplash.com/photo-1525253086316-d0c936c814f8?fit=crop&w=750&q=80"
        zoomSrc="https://images.unsplash.com/photo-1525253086316-d0c936c814f8?fit=crop&w=1500&q=80"
        :sources="[
          {
            srcSet: `https://images.unsplash.com/photo-1525253086316-d0c936c814f8?fit=crop&w=750, https://images.unsplash.com/photo-1525253086316-d0c936c814f8?fit=crop&w=1500 2x`,
            media: '(min-width: 768px)'
          },
          {
            srcSet: `https://images.unsplash.com/photo-1525253086316-d0c936c814f8?fit=crop&w=1000, https://images.unsplash.com/photo-1525253086316-d0c936c814f8?fit=crop&w=2000 2x`,
            media: '(min-width: 1024px)'
          }
        ]"
        :fullscreenOnMobile="true"
        :hideHint="true"
        :fadeDuration="0"
        :imgAttributes="{
          style: {
            transition: 'none'
          }
        }"
      />
    </section>

    <section>
      <h2>Drag Demo</h2>

      <demo
        src="https://images.unsplash.com/photo-1546527868-ccb7ee7dfa6a?fit=crop&w=1500&q=80"
        moveType="drag"
        :fullscreenOnMobile="false"
        :width="750"
        :height="500"
        :hasSpacer="true"
      />
    </section>

    <section>
      <h2>Zoom on Hover Demo</h2>

      <demo
        src="https://images.unsplash.com/photo-1519150268069-c094cfc0b3c8?fit=crop&w=750&q=80"
        zoomSrc="https://images.unsplash.com/photo-1519150268069-c094cfc0b3c8?fit=crop&w=1500&q=80"
        zoomType="hover"
        :fullscreenOnMobile="true"
        :zoomScale="0.9"
        :zoomPreload="true"
      />
    </section>
  </div>
</template>

<script>
import Demo from './Demo.vue';
import '../shared/styles.css';

export default {
  name: 'App',
  components: {
    Demo
  },
};
</script>

// sandbox/react/App.js
import React, { useRef } from 'react';
import Demo from './Demo';
import '../../packages/react/src/styles.css';
import '../shared/styles.css';

const App = () => {
  const ref = useRef();

  const handleZoom = () => {
    console.log('ref', ref.current);
  };

  return (
    <main>
      <h1>react-inner-image-zoom Sandbox</h1>

      <section>
        <h2>Pan Demo</h2>

        <Demo
          src="https://images.unsplash.com/photo-1630525037424-fc736b4fda86?fit=crop&w=750&q=80"
          zoomSrc="https://images.unsplash.com/photo-1630525037424-fc736b4fda86?fit=crop&w=1500&q=80"
          fullscreenOnMobile={true}
          imgAttributes={{
            title: 'Title',
            alt: 'Alt text',
            onLoad: () => console.log('Original image loaded'),
            'data-attribute': 'Data'
          }}
          ref={ref}
          afterZoomIn={handleZoom}
        />
      </section>

      <section>
        <h2>Drag Demo</h2>

        <Demo
          src="https://images.unsplash.com/photo-1622474413687-09fb95304d18?fit=crop&w=750&q=80"
          zoomSrc="https://images.unsplash.com/photo-1622474413687-09fb95304d18?fit=crop&w=1500&q=80"
          hideCloseButton={true}
          moveType="drag"
          zoomPreload={true}
          imgAttributes={{
            alt: 'Alt text'
          }}
        />
      </section>

      <section>
        <h2>Zoom on Hover Demo</h2>

        <Demo
          src="https://images.unsplash.com/photo-1547894233-3b986939e29c?fit=crop&w=750&q=80"
          zoomSrc="https://images.unsplash.com/photo-1547894233-3b986939e29c?fit=crop&w=1500&q=80"
          fullscreenOnMobile={true}
          hideHint={true}
          zoomPreload={true}
          zoomType="hover"
          imgAttributes={{
            alt: 'Alt text'
          }}
        />
      </section>
    </main>
  );
};

export default App;
